export const ADD_TO_SPRINT = "ADD_TO_SPRINT";
export const REMOVE_FROM_SPRINT = "REMOVE_FROM_SPRINT";
export const ADJUST_PHASE = "ADJUST_PHASE";
export const LOAD_CURRENT_METHOD = "LOAD_CURRENT_METHOD";